name: Java CI

on:
  push:
    branches:
      - EsanLamSing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11" # You can change this to the version you want

      - name: Compile Java
        run: |
          cd YourBranch/HolidayTravelVehicles 
          javac -d . *.java
        # Compile java files from the directory
